### ISSUE TITLE
show query progress in R

### ISSUE THREAD

**Issue by EdwinTh** [ianmcook/implyr#14]
When executing an Impala query from HUE the progress of the query is shown. It would be a nice-to-have in R as well. Similar to the progress bars from `readr` for reading large datasets.

![screen shot 2017-07-13 at 10 39 39](https://user-images.githubusercontent.com/7958036/28157760-d044a63c-67b7-11e7-840e-e2e5e8230803.png)

**Comment by ianmcook** [comment]
Interesting idea, thanks. I'm not sure about feasibility; I don't know if DBI provides any of the underlying tools that would be necessary to do this. Hue is able to do it because it uses a different interface to Impala (Apache Thrift) which includes this capability. With R and dplyr we're constrained by what DBI can do and by what's implemented in the DBI implementations (RJDBC, odbc). I'll look more into it.

**Comment by ianmcook** [comment]
AFAICT the underlying ODBC and JDBC layers don't provide a way to do this. I'll close this issue but I'll keep my eyes open because I agree that this would be a great enhancement.

**Comment by ianmcook** [comment]
Note for future reference: dplyr includes the function [`progress_estimated()`](http://dplyr.tidyverse.org/reference/progress_estimated.html) which can be used to display a progress bar. But implementing this (in a non-fake way) would require the ODBC/JDBC driver to provide progress information.
