### ISSUE TITLE
Check for compatibility with rlang 0.2.0

### ISSUE THREAD

**Issue by ianmcook** [ianmcook/implyr#18]
See the changes in https://github.com/tidyverse/dbplyr/pull/67 and check if any similar changes are required to implyr.

**Comment by mirekkolar** [comment]
Dear Ian

I've been working with **implyr** for few weeks without problems, but now when I updated its dependencies (including update to rlang 0.2.0, but also includes update of dplyr, dbplyr) I ran to serious problem - basically all summarise queries ceased to work. I think it is related to the compatibility question you asked yourself so I raise it here.

There is some problem with parsing variables to group_by - I'm running below simple code.

`index %>%
  summarize(divisor = sum(divisor)) %>%
  explain
`
Which gets translated like this:
`<SQL>
SELECT ``, SUM(`divisor`) AS `divisor`
FROM ds_cz_prod.index
GROUP BY ``
`
An error is thrown because of unintended grouping by empty variable. I can run this in parallel on a server where I updated implyr to latest version 0.2.2 but **did not** update the dependencies, and there it works normally, i.e. as
`<SQL>
SELECT SUM(`divisor`) AS `divisor`
FROM ds_cz_prod.index`

In attachment I include complete code I'm running on both machines, the result of explain statement, and the sessionInfo.
Let me note that I also switched to the latest Cloudera driver (working with JDBC) on my local workstation, but for both old and new driver the result is the same.

Please advise if there is something more I can check on my end, or if indeed some source code changes are needed?
[implyr issue #18.pdf](https://github.com/ianmcook/implyr/files/1806286/implyr.issue.18.pdf)


Thank you

**Comment by ianmcook** [comment]
Thanks @mirekkolar for reporting this and providing all the details!

I ran into this same error myself just hours ago. I have one environment where the error occurs and one where it does not occur, and when I compare the `sessionInfo()` output from those two sessions, the only difference I see is that the version of DBI is different (works on 0.7, fails on 0.8), so I believe this is related to a change in DBI, not in rlang. I will investigate further later today.

**Comment by ianmcook** [comment]
@mirekkolar I ran some more tests and confirmed that a change I already made to implyr on GitHub (https://github.com/ianmcook/implyr/commit/7ffdfbfeef400301e1af5931e7f57f5e819e3f21) fixes this problem.

I haven't published a new version of implyr on CRAN since this change, so if you're using the latest CRAN release version (0.2.2) then this problem will still affect you.

Can you install the development version of implyr from GitHub to see if this solves the problem for you?
`devtools::install_github("ianmcook/implyr")`

**Comment by mirekkolar** [comment]
@ianmcook thanks so much for your fast reaction -  yes with the development version all works well!

I cannot test the development version so easily in my server environment with older version of dependencies, for backwards compatibility - but based on the changes you referenced I don't think I should expect any problem there.

Thanks again and I hope the new version makes it to CRAN soon!

**Comment by ianmcook** [comment]
This is fixed in implyr version 0.2.3 on CRAN.
