### ISSUE TITLE
Cannot get unicode from impala

### ISSUE THREAD

**Issue by kiakaku** [ianmcook/implyr#28]
> library(odbc)
library(dplyr)
library(implyr)
drv <- odbc::odbc()
impala <- src_impala(
  drv = drv,
  driver = "Cloudera ODBC Driver for Impala",
  host = "impala-proxy",
  port = 21050,
  database = "default",
  uid = "username",
  pwd = "password"
)
data <- dbGetQuery(impala, "SELECT * FROM ghtk.package_logs limit 10")

Output: `Th<ea>m coupon E516188e`  for unicode string `Thêm coupon E516188e`

**Comment by ianmcook** [comment]
Character encoding problems are likely caused by locale settings in your installation of R or your operating system, encoding problems in the table data, or problems that existed in older versions of Impala or the Impala ODBC or JDBC drivers. I added a simple test in https://github.com/ianmcook/implyr/commit/d01949642afad714a5acaa5553edb706df62c25b that will cause the Travis builds of implyr to fail if some common characters with diacritical marks are not outputted correctly. Currently this test is passing.
