### ISSUE TITLE
Would like to connect to specific db using src_impala

### ISSUE THREAD

**Issue by jhlch** [ianmcook/implyr#3]
It would be nice to be able to connect to a specific database using src_impala instead of needing to use dbExecute(db, "use new_db").

**Comment by chezou** [comment]
just FYI, I created `tbl_change_db()` in sparklyr.
https://github.com/rstudio/sparklyr/pull/474/files#diff-df93ac01616b79a3ad2c2a1eb5c977a1R83

I will try to add same one for impyr.

**Comment by ianmcook** [comment]
If possible, I want to address this in such a way that the user can use idiomatic dplyr syntax rather than implyr-specific syntax. This is related to https://github.com/hadley/dplyr/issues/244 and https://github.com/rstats-db/DBI/issues/24.

**Comment by ianmcook** [comment]
The resolution of this should use forward-compatible syntax. That's not possible at the moment because Hadley and Kirill Müller and others are actively working to solve this problem in dplyr and DBI, and the syntax that will be used has not yet been decided. Closing this for now, but I will revisit it once there is an idiomatic syntax for this established by dyplr.

**Comment by chezou** [comment]
OK, it's a completely dplyr and DBI problem.

**Comment by ianmcook** [comment]
This is solved in dplyr 0.7.0 with the new function [`in_schema()`](http://dbplyr.tidyverse.org/reference/in_schema.html).
