### ISSUE TITLE
Cannot connect to database SASL error

### ISSUE THREAD

**Issue by FilipeamTeixeira** [ianmcook/implyr#31]
Whenever I try to connect to the impala database, I keep on getting this error:

`Error: nanodbc/nanodbc.cpp:950: HY000: [Cloudera][ThriftExtension] (4) Error occurred while contacting server: EAGAIN (timed out). The connection has been configured to not use SASL for authentication. This error might be due to the server has been configured to use SASL for authentication. `

I'm not sure if this is because often we have to connect through SSH but so far I've tried a lot of things unsuccessfully. Any idea of what might be happening here?

**Comment by ianmcook** [comment]
Hi Filipe, Timeout errors like this can be difficult to diagnose because they can have any number of different causes. What version of the Impala ODBC driver are you using? Can you copy and paste the R code you're using to try to connect (with the password and any other private details redacted)? Are you able to successfully connect to Impala from other clients on the same machine you're running this R code on? Knowing those things might give me some clues.
