### ISSUE TITLE
copy_to dimension limit

### ISSUE THREAD

**Issue by karoliskascenas** [ianmcook/implyr#49]
Is there any reason why [this](https://github.com/ianmcook/implyr/blob/a72e68e7a171b343362e4c23d450ac763d6d5d97/R/src_impala.R#L340-L349) limitation exists? I've rebuilt the package without it and was successfully able to write a 50000x5 table.

**Comment by ianmcook** [comment]
The only direct means implyr has of copying data from an R session into an Impala table is by running a SQL `INSERT ... VALUES()` statement, with the values to be inserted represented as literals in the statement. This method of loading data into Impala is kludgy and is inefficient for large amounts of data, and it is potentially difficult to cancel or undo. That's why this limit exists. Whenever possible, I'd encourage you to use a more efficient method of loading data into whatever storage system backs your Impala table. But I recognize that this implyr method might be your best option in some cases. The choice of the number 1000 was somewhat arbitrary. It was based on some informal tests I performed while connecting over the internet to a remote instance of Impala over an average speed internet connection. If you would like to submit a PR to make this limit configurable using `options()`, I will gladly merge it. Thank you.

**Comment by karoliskascenas** [comment]
https://github.com/ianmcook/implyr/pull/50
